name: ${SERVER_NAME}
services:
  web:
    build: .
    image: rs-server-ws
    command: /container_init.sh
    ports:
      - "${HOST_PORT_TO_BIND}:8765"   # port-of-host:port-of-container
    depends_on:
      db:
        condition: service_healthy
    environment:
      COORD_URL: ${COORD_URL}    # reading from the .env file
      HOST_PORT_TO_BIND: ${HOST_PORT_TO_BIND}
      HOST_IP: ${HOST_IP}
      FLASK_ENV : development
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: db
      MYSQL_DATABASE: server
      MYSQL_USER: mytestuser
      MYSQL_PASSWORD: 
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: server
      MYSQL_USER: mytestuser
      MYSQL_PASSWORD: 
    healthcheck:
      test: ["CMD", "mysql", "-u", "mytestuser"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s
    volumes:
      - ./server_sql_setup.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: