name: coord
services:
  web:
    build: .
    image: rs-coordinator-api
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_ENV : development
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: db
      MYSQL_DATABASE: coordinator
      MYSQL_USER: mytestuser
      MYSQL_PASSWORD: 
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coordinator
      MYSQL_USER: mytestuser
      MYSQL_PASSWORD: 
    healthcheck:
      test: ["CMD", "mysql", "-u", "mytestuser"]
      interval: 3s
      timeout: 1s
      retries: 4
      start_period: 20s
    volumes:
      - ./coordinator_sql_setup.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: